### ISSUE TITLE
call method with ref

### ISSUE THREAD

**Issue by trivalik** [davidebbo/ReflectionMagic#17]
When you wanna call `dynamicControl.DefWndProc(ref m);` it does not work. So I add to method `ParametersCompatible` the follow workarround:

```C#
               if (params1[i].ParameterType.IsByRef) {
                    var p2 = params2[i].GetType().MakeByRefType();
                    //TODO support derivation
                    if (params1[i].ParameterType != p2) {
                        return false;
                    }
                }
                else {
                    if (!params1[i].ParameterType.IsInstanceOfType(params2[i])) {
                        // Parameters should be instance of the parameter type.
                        return false;
                    }
                }
```

**Comment by jvandertil** [comment]
Thanks for bringing this up. I'll have a look if I can build in support for ByRef values.

**Comment by jvandertil** [comment]
Alright, I have a fixed version. Unfortunately .NET Core 1 does not support the calling of dynamic methods with 'ref' or 'out' parameters. This fails with a PlatformNotSupportedException and I've tried looking into it but it does not seem to be something I can fix.

**Comment by davidebbo** [comment]
Maybe it's time to leave .NET Core 1.x support behind?

**Comment by jvandertil** [comment]
It's worth considering, but since it only affects ref and out parameters I'm not willing to leave it behind just yet. I'll put it in the release notes and in the README so that it is clear that it is not supported.

Expect a beta package with these fixes later today.

**Comment by davidebbo** [comment]
Fair enough.
