### ISSUE TITLE
Restore strong naming

### ISSUE THREAD

**Issue by jvandertil** [davidebbo/ReflectionMagic#8]
In #6 the strong naming build step was removed, this should be restored. This will probably coincide with #7.

**Comment by davidebbo** [comment]
Do you want to try to get a release out before this change? If we do, we should make it prerelease (e.g. 3.0.0-beta1), because adding the strong naming later is a breaking change.

**Comment by jvandertil** [comment]
Yes, I would like to get a 3.0.0-alpha/beta release out before this change happens. While currently removed from the project files, it is possible to create a signed assembly using project.json. The conditional in the original project was quite nice, but I believe conditionals don't work in project.json.

To create a signed build just add this to the project.json file:
```
"buildOptions": {
    "publicSign": true,
    "keyFile": "<path to key file>"
},
```

I've already ported the project to .csproj in my [fork](https://github.com/jvandertil/ReflectionMagic/tree/dotnetcore-csproj). The new csproj format is considered alpha and breaks compatibility with VS2015, which is unfortunate as that is what I'm currently using day to day.

So, I'm currently holding off on merging that in till it stabilizes.

**Comment by jvandertil** [comment]
Before I forget, how are we going to approach signing the assembly? Is that something you want to keep doing? Or should we generate a new SNK file and check that in? If the latter, then I can bring back the strong naming quite easily, as described above.

**Comment by davidebbo** [comment]
Good question. I think generating a new one is the way to go. It's a breaking change of course, but new major version, so we have some freedom.

Also, if you give me your nuget ID, I'll add you as package owner.

**Comment by jvandertil** [comment]
My NuGet ID is the same as my username here :). I'll take a look at adding a new SNK tomorrow.
